"""
/***************************************************************************
 SaarlandGeobasisdatenWMS
                                 A QGIS plugin
 WMS downloader from Saarland's geoportal
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-12
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Template Inc
        email                : example@email.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import (
    QSettings,
    QTranslator,
    QCoreApplication,
    QObject,
    pyqtSignal,
    QRunnable,
    QThreadPool,
    QMutex,
    QTimer,
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QProgressDialog
import logging
import time


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


if not logger.handlers:
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)


from .resources import *

from .saarland_geoportal_dialog import SaarlandGeobasisdatenWMSDialog
import os.path


class LayerProcessingSignals(QObject):
    """Signals for communicating between worker threads and main thread."""

    layer_processed = pyqtSignal(str, bool, str, object)
    progress_updated = pyqtSignal(int)


class LayerWorker(QRunnable):
    """Worker thread for processing individual layers."""

    def __init__(self, layer_data, plugin_instance, worker_id):
        super().__init__()
        self.layer_data = layer_data
        self.plugin = plugin_instance
        self.worker_id = worker_id
        self.signals = LayerProcessingSignals()

    def run(self):
        """Process a single layer in a worker thread."""
        name = self.layer_data["name"]
        title = self.layer_data["title"]
        srs_list = self.layer_data.get("srs", [])
        base_url = self.layer_data["url"]
        service_type = self.layer_data.get("service_type", "WMS")

        logger.info(
            f"Worker {self.worker_id}: Processing layer: {name} ({service_type})"
        )

        try:
            layer = self.plugin._process_single_layer(self.layer_data)
            if layer and layer.isValid():
                self.signals.layer_processed.emit(name, True, "", layer)
            else:
                error = (
                    layer.error().message()
                    if layer and layer.error()
                    else "Unknown error"
                )
                self.signals.layer_processed.emit(name, False, error, None)
        except Exception as e:
            error_msg = str(e)
            logger.error(
                f"Worker {self.worker_id}: Exception processing layer '{name}': {error_msg}"
            )
            self.signals.layer_processed.emit(name, False, error_msg, None)


class SaarlandGeobasisdatenWMS:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """

        self.iface = iface

        self.plugin_dir = os.path.dirname(__file__)

        locale = QSettings().value("locale/userLocale")[0:2]
        locale_path = os.path.join(
            self.plugin_dir, "i18n", "SaarlandGeobasisdatenWMS_{}.qm".format(locale)
        )

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.menu = self.tr("&SaarlandGeobasisdatenWMS")

        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """

        return QCoreApplication.translate("SaarlandGeobasisdatenWMS", message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:

            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToDatabaseMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/saarland_geoportal/icon.png"
        self.add_action(
            icon_path,
            text=self.tr("SaarlandOpendataWMS"),
            callback=self.run,
            parent=self.iface.mainWindow(),
        )

        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginDatabaseMenu(self.tr("&SaarlandGeobasisdatenWMS"), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""

        if self.first_start:
            self.first_start = False
            self.dlg = SaarlandGeobasisdatenWMSDialog()

        self.dlg.load_with_loading_dialog()

        self.dlg.reset_selection()

        self.dlg.show()

        result = self.dlg.exec_()

        if result:

            selected_layers = self.dlg.get_selected_layers()

            if not selected_layers:
                from qgis.PyQt.QtWidgets import QMessageBox

                QMessageBox.warning(
                    self.iface.mainWindow(),
                    "No Layers Selected",
                    "Please select at least one layer to import.",
                )
                return

            try:
                self.add_selected_layers(selected_layers)
            except Exception as e:
                from qgis.PyQt.QtWidgets import QMessageBox

                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Error",
                    "Error adding WMS layers: {}".format(str(e)),
                )
                print("Error adding WMS layers:", e)

    def _prewarm_caps(self, base_url: str):
        """Pre-warm cookies by hitting the same base with a capabilities call.

        This ensures the PHPSESSID lands in the cookie jar that QGIS uses,
        preventing "Cannot calculate extent" errors on first load.
        """
        try:
            if not base_url:
                return
            from qgis.core import QgsNetworkAccessManager
            from qgis.PyQt.QtNetwork import QNetworkRequest
            from qgis.PyQt.QtCore import QEventLoop, QUrl

            url = (
                base_url
                + ("&" if "?" in base_url else "?")
                + "service=WMS&request=GetCapabilities"
            )
            nam = QgsNetworkAccessManager.instance().networkAccessManager()
            req = QNetworkRequest(QUrl(url))
            req.setRawHeader(b"Referer", b"https://geoportal.saarland.de/")
            loop = QEventLoop()
            reply = nam.get(req)
            reply.finished.connect(loop.quit)
            loop.exec_()
            logger.debug(f"Pre-warmed capabilities for: {base_url}")
        except Exception as e:
            logger.debug(f"Pre-warm failed (non-critical): {e}")
            pass

    def _debug_layer_connection(self, uri: str, layer_name: str):
        """Debug function to help understand layer connection issues."""
        logger.warning(f"=== DEBUGGING LAYER: {layer_name} ===")
        logger.warning(f"Full URI: {uri}")

        import re

        url_match = re.search(r"url=([^&]+)", uri)
        if url_match:
            base_url = url_match.group(1)
            logger.warning(f"Base URL: {base_url}")

            try:
                import urllib.request

                caps_url = (
                    base_url
                    + ("&" if "?" in base_url else "?")
                    + "REQUEST=GetCapabilities&SERVICE=WMS"
                )

                req = urllib.request.Request(caps_url)
                req.add_header("Referer", "https://geoportal.saarland.de/")
                req.add_header("User-Agent", "QGIS/3.28")

                with urllib.request.urlopen(req, timeout=10) as response:
                    content = response.read()[:1000].decode("utf-8", errors="ignore")
                    if "ServiceException" in content:
                        logger.warning(f"GetCapabilities returned error: {content}")
                    else:
                        logger.warning(
                            f"GetCapabilities OK (first 200 chars): {content[:200]}"
                        )

            except Exception as e:
                logger.warning(f"GetCapabilities test failed: {e}")

        logger.warning(f"=== END DEBUG ===")

        try:
            test_uri = f"url={base_url}&layers={layer_name}&format=image/png"
            logger.warning(f"Testing minimal URI: {test_uri}")
        except:
            pass

    def _create_layer_via_qgis_wms(
        self, base_url: str, layer_name: str, layer_title: str, crs: str
    ):
        """Try to create WMS layer using QGIS's native WMS connection approach."""
        from qgis.core import QgsDataSourceUri, QgsRasterLayer

        uri = QgsDataSourceUri()

        uri.setParam("url", base_url)
        uri.setParam("layers", layer_name)
        uri.setParam("styles", "")
        uri.setParam("format", "image/png")
        uri.setParam("srs", crs)

        uri.setParam("transparent", "true")

        uri.setParam("http-header:referer", "https://geoportal.saarland.de/")

        layer = QgsRasterLayer(
            uri.encodedUri().data().decode(), layer_title or layer_name, "wms"
        )

        logger.debug(f"QGIS native URI: {uri.encodedUri().data().decode()}")
        return layer

    def _try_alternative_wms_approaches(
        self, base_url: str, layer_name: str, layer_title: str, crs: str
    ):
        """Try alternative approaches for problematic WMS layers."""
        approaches = []

        try:
            import urllib.parse

            parsed = urllib.parse.urlparse(base_url)

            getmap_params = {
                "SERVICE": "WMS",
                "VERSION": "1.1.1",
                "REQUEST": "GetMap",
                "LAYERS": layer_name,
                "STYLES": "",
                "FORMAT": "image/png",
                "SRS": crs,
                "BBOX": "0,0,1,1",
                "WIDTH": "256",
                "HEIGHT": "256",
                "TRANSPARENT": "true",
            }

            existing_params = urllib.parse.parse_qs(parsed.query)

            all_params = {}
            for key, values in existing_params.items():
                all_params[key] = values[0] if values else ""
            all_params.update(getmap_params)

            query_string = urllib.parse.urlencode(all_params)
            direct_url = (
                f"{parsed.scheme}://{parsed.netloc}{parsed.path}?{query_string}"
            )

            direct_uri = f"url={parsed.scheme}://{parsed.netloc}{parsed.path}?{urllib.parse.urlencode({k: v for k, v in all_params.items() if k not in ['REQUEST', 'BBOX', 'WIDTH', 'HEIGHT']})}"

            approaches.append(("Direct service", direct_uri))

        except Exception as e:
            logger.debug(f"Direct approach failed to construct: {e}")

        try:
            minimal_uri = f"url={base_url.split('?')[0]}?layer_id=31261&layers={layer_name}&format=image/png&srs={crs}"
            approaches.append(("Minimal with layer_id", minimal_uri))
        except:
            pass

        from qgis.core import QgsRasterLayer

        for approach_name, uri in approaches:
            try:
                logger.warning(f"Trying {approach_name}: {uri}")
                layer = QgsRasterLayer(uri, layer_title or layer_name, "wms")
                if layer.isValid():
                    logger.warning(f"✓ {approach_name} approach worked!")
                    return layer
                else:
                    error = (
                        layer.error().message() if layer.error() else "Unknown error"
                    )
                    logger.warning(f"✗ {approach_name} failed: {error}")
            except Exception as e:
                logger.warning(f"✗ {approach_name} exception: {e}")

        return None

    def _create_layer_with_connection_test(
        self, base_url: str, layer_name: str, layer_title: str, crs: str
    ):
        """Create layer with preliminary connection testing."""
        try:

            logger.warning(f"Testing WMS connection for {layer_name}")

            import urllib.request
            import urllib.parse

            parsed = urllib.parse.urlparse(base_url)
            caps_params = urllib.parse.parse_qs(parsed.query)
            caps_params["REQUEST"] = ["GetCapabilities"]
            caps_params["SERVICE"] = ["WMS"]

            caps_query = urllib.parse.urlencode(caps_params, doseq=True)
            caps_url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}?{caps_query}"

            req = urllib.request.Request(caps_url)
            req.add_header("Referer", "https://geoportal.saarland.de/")
            req.add_header("User-Agent", "QGIS/3.28")

            with urllib.request.urlopen(req, timeout=10) as response:
                caps_content = response.read(1000).decode("utf-8", errors="ignore")
                if "ServiceException" in caps_content:
                    logger.warning(
                        f"GetCapabilities returned error: {caps_content[:200]}"
                    )
                    return None
                elif layer_name not in caps_content:
                    logger.warning(f"Layer {layer_name} not found in capabilities")

                else:
                    logger.warning(f"Layer {layer_name} found in capabilities")

            from qgis.core import QgsRasterLayer

            simple_uri = (
                f"url={base_url}&layers={layer_name}&format=image/png&srs={crs}"
            )

            logger.warning(f"Creating layer with simple URI: {simple_uri}")
            layer = QgsRasterLayer(simple_uri, layer_title or layer_name, "wms")

            return layer

        except Exception as e:
            logger.warning(f"Connection test approach failed: {e}")
            return None

    def add_selected_layers(self, selected_layers):
        """Add selected WMS/WFS layers to the project using multithreading.

        Args:
            selected_layers: List of dicts with keys 'name', 'title', 'srs', 'url', 'service_type'
        """
        logger.info(
            f"Adding {len(selected_layers)} selected layers to project (multithreaded)"
        )

        if not selected_layers:
            return

        self._processing_mutex = QMutex()
        self._added_count = 0
        self._failed_layers = []
        self._processed_count = 0
        self._total_layers = len(selected_layers)

        self._progress_dialog = QProgressDialog(
            "Processing layers...",
            "Cancel",
            0,
            self._total_layers,
            self.iface.mainWindow(),
        )
        self._progress_dialog.setWindowTitle("Adding Layers")
        self._progress_dialog.setAutoClose(False)
        self._progress_dialog.setAutoReset(False)
        self._progress_dialog.show()

        self._thread_pool = QThreadPool()
        max_threads = min(8, len(selected_layers))
        self._thread_pool.setMaxThreadCount(max_threads)

        logger.info(f"Using {max_threads} threads for processing")

        for i, layer_data in enumerate(selected_layers):
            worker = LayerWorker(layer_data, self, i)
            worker.signals.layer_processed.connect(self._on_layer_processed)
            self._thread_pool.start(worker)

        self._completion_timer = QTimer()
        self._completion_timer.timeout.connect(self._check_completion)
        self._completion_timer.start(100)

    def _on_layer_processed(self, layer_name, success, error_msg, layer_object):
        """Handle the result of a processed layer (runs on main thread)."""
        from qgis.core import QgsProject

        self._processing_mutex.lock()
        try:
            self._processed_count += 1

            if success and layer_object:
                logger.info(f"Successfully processed layer: {layer_name}")
                QgsProject.instance().addMapLayer(layer_object)
                self._added_count += 1
            else:
                logger.error(f"Failed to process layer '{layer_name}': {error_msg}")
                self._failed_layers.append(f"{layer_name}: {error_msg}")

            if self._progress_dialog:
                self._progress_dialog.setValue(self._processed_count)
                self._progress_dialog.setLabelText(
                    f"Processing layers... ({self._processed_count}/{self._total_layers})\n"
                    f"Added: {self._added_count}, Failed: {len(self._failed_layers)}"
                )
        finally:
            self._processing_mutex.unlock()

    def _check_completion(self):
        """Check if all workers have completed processing."""
        if self._processed_count >= self._total_layers or (
            self._progress_dialog and self._progress_dialog.wasCanceled()
        ):
            self._completion_timer.stop()

            self._thread_pool.waitForDone(5000)

            if self._progress_dialog:
                self._progress_dialog.close()
                self._progress_dialog = None

            self._show_completion_message()

    def _show_completion_message(self):
        """Show the final completion message."""
        from qgis.PyQt.QtWidgets import QMessageBox

        logger.info(
            f"Layer addition complete: {self._added_count} added, {len(self._failed_layers)} failed"
        )

        msg = f"Successfully added {self._added_count} layer(s) to the project."
        if self._failed_layers:
            msg += f"\n\nFailed to add {len(self._failed_layers)} layer(s):\n"
            msg += "\n".join(self._failed_layers[:5])
            if len(self._failed_layers) > 5:
                msg += f"\n... and {len(self._failed_layers) - 5} more"

        QMessageBox.information(self.iface.mainWindow(), "Import Complete", msg)

    def _process_single_layer(self, layer_data):
        """Process a single layer (extracted from original logic for use in worker threads).

        Args:
            layer_data: Dict with keys 'name', 'title', 'srs', 'url', 'service_type'

        Returns:
            QgsRasterLayer or QgsVectorLayer: The created layer, or None if failed
        """
        from qgis.core import QgsRasterLayer, QgsVectorLayer

        name = layer_data["name"]
        title = layer_data["title"]
        srs_list = layer_data.get("srs", [])
        base_url = layer_data["url"]
        service_type = layer_data.get("service_type", "WMS")

        logger.debug(f"Processing single layer: {name} ({service_type})")
        logger.debug(f"  Title: {title}")
        logger.debug(f"  SRS list: {srs_list}")
        logger.debug(f"  Base URL: {base_url}")

        crs = "EPSG:3857"
        if "EPSG:25832" in srs_list:
            crs = "EPSG:25832"
        elif "EPSG:3857" in srs_list:
            crs = "EPSG:3857"
        elif srs_list:
            crs = srs_list[0]

        logger.debug(f"  Selected CRS: {crs}")

        if service_type == "WMS":

            base = layer_data.get("service_url") or layer_data.get("url") or ""

            if base.endswith("?"):
                base = base[:-1]

            if "SERVICE=" not in base.upper():
                sep = "&" if "?" in base else "?"
                base = f"{base}{sep}SERVICE=WMS"

            crs = "EPSG:4326"
            if "EPSG:25832" in srs_list:
                crs = "EPSG:25832"
            elif srs_list:
                crs = srs_list[0]

            if name in ("sl_alk", "sl_alk_info"):
                logger.warning(f"DEBUG sl_* layer: {name}, base: {base}")

            layer = None

            fast_uri = (
                f"url={base}&"
                f"layers={name}&"
                f"styles=&"
                f"format=image/png&"
                f"srs={crs}&"
                f"version=1.1.1"
            )
            logger.debug(f"  Trying fast approach for {name}: {fast_uri}")
            layer = QgsRasterLayer(fast_uri, title or name, "wms")

            if not layer.isValid():
                from qgis.core import QgsMessageLog, Qgis

                QgsMessageLog.logMessage(
                    f"Fast approach failed for {name}, trying comprehensive approach...",
                    "Saarland Geoportal",
                    Qgis.Warning,
                )

                uri_formats = []

                uri1 = (
                    f"url={base}&"
                    f"layers={name}&"
                    f"styles=&"
                    f"format=image/png&"
                    f"srs={crs}&"
                    f"version=1.1.1&"
                    f"transparent=true&"
                    f"http-header:referer=https://geoportal.saarland.de/"
                )
                uri_formats.append(("Standard with SRS", uri1))

                uri2 = (
                    f"url={base}&"
                    f"layers={name}&"
                    f"styles=&"
                    f"format=image/png&"
                    f"srs=EPSG:4326&"
                    f"version=1.1.1&"
                    f"transparent=true&"
                    f"http-header:referer=https://geoportal.saarland.de/"
                )
                uri_formats.append(("EPSG:4326", uri2))

                uri3 = f"url={base}&layers={name}&format=image/png&srs={crs}"
                uri_formats.append(("Minimal", uri3))

                clean_base = base.split("?")[0]
                mapbender_url = f"{clean_base}?layer_id=31261&withChilds=1&SERVICE=WMS&VERSION=1.1.1"
                uri4 = (
                    f"url={mapbender_url}&"
                    f"layers={name}&"
                    f"styles=&"
                    f"format=image/png&"
                    f"srs={crs}&"
                    f"version=1.1.1&"
                    f"http-header:referer=https://geoportal.saarland.de/"
                )
                uri_formats.append(("Clean base with Mapbender URL", uri4))

                uri5 = (
                    f"url={base}&"
                    f"layers={name}&"
                    f"styles=&"
                    f"format=image/png&"
                    f"srs={crs}&"
                    f"http-header:referer=https://geoportal.saarland.de/"
                )
                uri_formats.append(("No duplicate version", uri5))

                layer = None
                for format_name, uri in uri_formats:
                    logger.debug(f"  Trying {format_name} format: {uri}")
                    test_layer = QgsRasterLayer(uri, title or name, "wms")
                    if test_layer.isValid():
                        logger.info(
                            f"  ✓ {format_name} format worked for layer '{name}'"
                        )
                        QgsMessageLog.logMessage(
                            f"✅ {format_name} approach worked for {name}!",
                            "Saarland Geoportal",
                            Qgis.Info,
                        )
                        layer = test_layer
                        break
                    else:
                        error = (
                            test_layer.error().message()
                            if test_layer.error()
                            else "Unknown error"
                        )
                        logger.debug(f"  ✗ {format_name} format failed: {error}")

                if layer is None:
                    QgsMessageLog.logMessage(
                        f"🔍 Standard formats failed for {name}, trying alternative approaches...",
                        "Saarland Geoportal",
                        Qgis.Warning,
                    )

                    try:
                        alt_layer = self._try_alternative_wms_approaches(
                            base, name, title, crs
                        )
                        if alt_layer and alt_layer.isValid():
                            QgsMessageLog.logMessage(
                                f"✅ Alternative approach worked for {name}!",
                                "Saarland Geoportal",
                                Qgis.Info,
                            )
                            layer = alt_layer
                    except Exception as e:
                        logger.debug(f"Alternative approaches failed: {e}")

                    if layer is None:
                        try:
                            layer = self._create_layer_via_qgis_wms(
                                base, name, title, crs
                            )
                            if layer and layer.isValid():
                                QgsMessageLog.logMessage(
                                    f"✅ QGIS native approach worked for {name}!",
                                    "Saarland Geoportal",
                                    Qgis.Info,
                                )
                        except Exception as e:
                            logger.debug(f"QGIS native approach failed: {e}")

                    if layer is None:
                        try:
                            layer = self._create_layer_with_connection_test(
                                base, name, title, crs
                            )
                            if layer and layer.isValid():
                                QgsMessageLog.logMessage(
                                    f"✅ Connection test approach worked for {name}!",
                                    "Saarland Geoportal",
                                    Qgis.Info,
                                )
                        except Exception as e:
                            logger.debug(f"Connection test approach failed: {e}")
            else:

                logger.debug(f"  ✓ Fast approach worked for layer '{name}'")

            if name in ("sl_alk", "sl_alk_info"):
                from qgis.core import QgsMessageLog, Qgis

                if layer is not None:
                    QgsMessageLog.logMessage(
                        f"🎉 SUCCESS! We have a valid layer for {name} from comprehensive approach!",
                        "Saarland Geoportal",
                        Qgis.Info,
                    )
                else:
                    QgsMessageLog.logMessage(
                        f"❌ No valid layer created for {name}, using fallback",
                        "Saarland Geoportal",
                        Qgis.Critical,
                    )
                    logger.warning(
                        f"DEBUG sl_* final URI -> {uri_formats[0][1] if 'uri_formats' in locals() else 'No URI'}"
                    )
                    if "uri_formats" in locals():
                        self._debug_layer_connection(uri_formats[0][1], name)

            if layer is None:
                uri = (
                    uri_formats[0][1]
                    if "uri_formats" in locals() and uri_formats
                    else f"url={base}&layers={name}&format=image/png&srs={crs}"
                )
                logger.debug(f"  Fallback WMS URI: {uri}")
                layer = QgsRasterLayer(uri, title or name, "wms")

        elif service_type == "WFS":

            import os.path
            from urllib.parse import urlparse, urlunparse

            parsed = urlparse(base_url)

            normalized_path = os.path.normpath(parsed.path)

            normalized_url = urlunparse(
                (
                    parsed.scheme,
                    parsed.netloc,
                    normalized_path,
                    parsed.params,
                    parsed.query,
                    parsed.fragment,
                )
            )

            uri = "pagingEnabled='true' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='{crs}' typename='{name}' url='{url}' version='2.0.0'".format(
                url=normalized_url, name=name, crs=crs
            )
            logger.debug(f"  WFS URI: {uri}")
            layer = QgsVectorLayer(uri, title or name, "WFS")
        else:

            logger.warning(f"Unsupported service type: {service_type} for layer {name}")
            raise ValueError(f"Unsupported service type: {service_type}")

        return layer
