"""
/***************************************************************************
 SaarlandGeobasisdatenWMSDialog
                                 A QGIS plugin
 WMS downloader from Saarland's geoportal
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-12
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Template Inc
        email                : example@email.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import json
import logging
import sys
import subprocess
from io import StringIO
from contextlib import redirect_stdout, redirect_stderr

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


if not logger.handlers:
    console_handler = logging.StreamHandler()
    console_handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    console_handler.setFormatter(formatter)
    logger.addHandler(console_handler)


FORM_CLASS, _ = uic.loadUiType(
    os.path.join(os.path.dirname(__file__), "saarland_geoportal_dialog_base.ui")
)


class SaarlandGeobasisdatenWMSDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SaarlandGeobasisdatenWMSDialog, self).__init__(parent)

        self.setupUi(self)

        self.geo_links = self.load_geo_links_json()

        self.layers_tree.setHeaderLabel("Saarland Geoportal Services")
        self.layers_tree.setColumnCount(1)

        self.layers_tree.setStyleSheet("""
            QTreeView::indicator:unchecked {
                background-color: white;
                border: 2px solid #555555;
                width: 16px;
                height: 16px;
            }
            QTreeView::indicator:checked {
                background-color: #2196F3;
                border: 2px solid #1976D2;
                width: 16px;
                height: 16px;
                image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHZpZXdCb3g9IjAgMCAxNiAxNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8cGF0aCBkPSJNIDMgOCBMIDYgMTEgTCAxMyA0IiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiIC8+Cjwvc3ZnPg==);
            }
            QTreeView::indicator:indeterminate {
                background-color: #90CAF9;
                border: 2px solid #1976D2;
                width: 16px;
                height: 16px;
            }
            QTreeView::indicator:unchecked:hover {
                background-color: #f0f0f0;
                border: 2px solid #2196F3;
            }
            QTreeView::indicator:checked:hover {
                background-color: #1976D2;
                border: 2px solid #0D47A1;
            }
        """)

        self.load_all_button.clicked.connect(self.load_all_sources)
        self.layers_tree.itemExpanded.connect(self.on_item_expanded)
        self.layers_tree.itemChanged.connect(self.on_item_changed)

        self.button_box.button(QtWidgets.QDialogButtonBox.Ok).setEnabled(True)

        self.build_tree_from_json()

        for i in range(self.layers_tree.topLevelItemCount()):
            top_item = self.layers_tree.topLevelItem(i)
            top_item.setExpanded(True)

            self.collapse_all_children(top_item)

    def load_with_loading_dialog(self):
        """Show a loading dialog and load all sources synchronously."""
        from qgis.PyQt.QtCore import Qt

        loading_dialog = QtWidgets.QDialog(self.parent())
        loading_dialog.setWindowTitle("Loading Geoportal Services")
        loading_dialog.setModal(True)
        loading_dialog.setWindowFlags(
            Qt.Dialog | Qt.CustomizeWindowHint | Qt.WindowTitleHint
        )

        layout = QtWidgets.QVBoxLayout(loading_dialog)

        label = QtWidgets.QLabel(
            "Loading all WMS/WFS services from Saarland Geoportal...\nPlease wait..."
        )
        label.setAlignment(Qt.AlignCenter)
        layout.addWidget(label)

        progress = QtWidgets.QProgressBar()
        progress.setRange(0, 0)
        layout.addWidget(progress)

        self.loading_status_label = QtWidgets.QLabel("Initializing...")
        self.loading_status_label.setAlignment(Qt.AlignCenter)
        self.loading_status_label.setWordWrap(True)
        layout.addWidget(self.loading_status_label)

        loading_dialog.resize(400, 150)

        loading_dialog.show()

        QtWidgets.QApplication.processEvents()

        try:

            self.loading_status_label.setText(
                "Fetching capabilities from 41 services..."
            )
            QtWidgets.QApplication.processEvents()

            self.load_all_sources_silent()

            loading_dialog.close()

        except Exception as e:
            loading_dialog.close()
            QtWidgets.QMessageBox.critical(
                self.parent(),
                "Error Loading Services",
                "Failed to load geoportal services:\n{}".format(str(e)),
            )

    def load_all_sources_silent(self):
        """Load all sources without updating the main dialog's status label."""
        total_loaded = 0
        errors = []

        def load_recursive(parent_item):
            nonlocal total_loaded, errors
            for i in range(
                parent_item.childCount()
                if hasattr(parent_item, "childCount")
                else self.layers_tree.topLevelItemCount()
            ):
                if hasattr(parent_item, "child"):
                    item = parent_item.child(i)
                else:
                    item = self.layers_tree.topLevelItem(i)

                item_type = item.data(0, Qt.UserRole + 2)

                if item_type == "service":

                    service_data = item.data(0, Qt.UserRole)
                    if service_data and not service_data.get("is_loaded", False):
                        try:

                            self.loading_status_label.setText(
                                "Loading: {}...".format(item.text(0))
                            )
                            QtWidgets.QApplication.processEvents()

                            count = self.load_layers_for_service(item, service_data)
                            total_loaded += count
                        except Exception as e:
                            errors.append("{}: {}".format(item.text(0), str(e)))
                elif item_type == "category":

                    load_recursive(item)

        load_recursive(self.layers_tree)

        if errors:
            self.status_label.setText(
                "Loaded {} layers with some errors. See console for details.".format(
                    total_loaded
                )
            )
            for error in errors:
                print("Error loading source:", error)
        else:
            self.status_label.setText(
                "Successfully loaded {} layers from all sources. Check layers to import.".format(
                    total_loaded
                )
            )

    def collapse_all_children(self, item):
        """Recursively collapse all children of an item."""
        for i in range(item.childCount()):
            child = item.child(i)
            child.setExpanded(False)
            self.collapse_all_children(child)

    def on_item_changed(self, item, column):
        """Handle checkbox state changes - let Qt manage tristate automatically."""

        pass

    def set_children_check_state(self, item, check_state):
        """Recursively set check state for all children."""
        for i in range(item.childCount()):
            child = item.child(i)
            child.setCheckState(0, check_state)

            self.set_children_check_state(child, check_state)

    def update_parent_check_state(self, item):
        """Update parent's check state based on children's states."""
        parent = item.parent()
        if parent is None:
            return

        checked_count = 0
        unchecked_count = 0
        partial_count = 0

        for i in range(parent.childCount()):
            child = parent.child(i)
            state = child.checkState(0)
            if state == Qt.Checked:
                checked_count += 1
            elif state == Qt.Unchecked:
                unchecked_count += 1
            else:
                partial_count += 1

        total = parent.childCount()
        new_state = None
        if checked_count == total:
            new_state = Qt.Checked
        elif unchecked_count == total:
            new_state = Qt.Unchecked
        else:
            new_state = Qt.PartiallyChecked

        if parent.checkState(0) != new_state:
            parent.setCheckState(0, new_state)

            self.update_parent_check_state(parent)

    def load_geo_links_json(self):
        """Load the geo links JSON file, refreshing it first with the link finder."""
        print("=== PLUGIN DEBUG: Starting load_geo_links_json ===")
        logger.info("Loading geo links JSON - starting link finder refresh...")
        
        # First, run the link finder to refresh the JSON
        print("=== PLUGIN DEBUG: About to run link finder ===")
        self._run_link_finder()
        print("=== PLUGIN DEBUG: Link finder completed ===")
        
        json_path = os.path.join(
            os.path.dirname(__file__), "link-finder", "saarland_geo_links.json"
        )
        logger.info(f"Loading JSON from: {json_path}")
        print(f"=== PLUGIN DEBUG: Loading JSON from {json_path} ===")
        
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                link_count = data.get('summary', {}).get('total_links', 0)
                logger.info(f"Successfully loaded JSON with {link_count} links")
                print(f"=== PLUGIN DEBUG: Successfully loaded {link_count} links ===")
                return data
        except Exception as e:
            logger.error(f"Error loading geo links JSON: {e}")
            print(f"=== PLUGIN DEBUG: ERROR loading JSON: {e} ===")
            return {"categories": {}}
    
    def _run_link_finder(self):
        """Run the link finder script to refresh the JSON file, suppressing output."""
        print("=== PLUGIN DEBUG: _run_link_finder started ===")
        logger.info("Starting link finder execution...")
        
        finder_script_path = os.path.join(
            os.path.dirname(__file__), "link-finder", "finder.py"
        )
        logger.info(f"Finder script path: {finder_script_path}")
        print(f"=== PLUGIN DEBUG: Finder script path: {finder_script_path} ===")
        
        if not os.path.exists(finder_script_path):
            logger.error(f"Finder script not found at: {finder_script_path}")
            print(f"=== PLUGIN DEBUG: ERROR - Finder script not found ===")
            return
        
        try:
            # Change to the link-finder directory so the script runs in the right context
            original_cwd = os.getcwd()
            link_finder_dir = os.path.dirname(finder_script_path)
            logger.info(f"Changing working directory from {original_cwd} to {link_finder_dir}")
            print(f"=== PLUGIN DEBUG: Changing to directory: {link_finder_dir} ===")
            os.chdir(link_finder_dir)
            
            # Add the link-finder directory to Python path temporarily
            if link_finder_dir not in sys.path:
                sys.path.insert(0, link_finder_dir)
                path_added = True
                logger.info(f"Added link finder directory to sys.path: {link_finder_dir}")
                print("=== PLUGIN DEBUG: Added link finder to sys.path ===")
            else:
                path_added = False
                logger.info("Link finder directory already in sys.path")
                print("=== PLUGIN DEBUG: Link finder already in sys.path ===")
            
            # Also add the vendor directory for dependencies
            vendor_dir = os.path.join(os.path.dirname(__file__), 'vendor')
            logger.info(f"Vendor directory path: {vendor_dir}")
            print(f"=== PLUGIN DEBUG: Vendor directory: {vendor_dir} ===")
            
            if not os.path.exists(vendor_dir):
                logger.error(f"Vendor directory not found: {vendor_dir}")
                print("=== PLUGIN DEBUG: ERROR - Vendor directory not found ===")
                return
                
            if vendor_dir not in sys.path:
                sys.path.insert(0, vendor_dir)
                vendor_path_added = True
                logger.info(f"Added vendor directory to sys.path: {vendor_dir}")
                print("=== PLUGIN DEBUG: Added vendor to sys.path ===")
            else:
                vendor_path_added = False
                logger.info("Vendor directory already in sys.path")
                print("=== PLUGIN DEBUG: Vendor already in sys.path ===")
            
            # Log current sys.path for debugging
            logger.info(f"Current sys.path (first 3 entries): {sys.path[:3]}")
            
            try:
                logger.info("Attempting to import finder module...")
                print("=== PLUGIN DEBUG: Importing finder module ===")
                import finder
                logger.info("Successfully imported finder module")
                print("=== PLUGIN DEBUG: Finder module imported successfully ===")
                
                # Create a new finder instance and run it
                logger.info("Creating SaarlandGeoLinkFinder instance...")
                print("=== PLUGIN DEBUG: Creating finder instance ===")
                link_finder = finder.SaarlandGeoLinkFinder()
                logger.info("Finder instance created successfully")
                print("=== PLUGIN DEBUG: Finder instance created ===")
                
                main_url = "https://geoportal.saarland.de/app-article/geobasisdatenuebersicht/"
                logger.info(f"Starting crawl of main URL: {main_url}")
                print(f"=== PLUGIN DEBUG: Starting crawl of {main_url} ===")
                
                link_finder.crawl_page(main_url, max_depth=1)
                logger.info("Crawling completed")
                print("=== PLUGIN DEBUG: Crawling completed ===")
                
                logger.info("Saving results to JSON...")
                print("=== PLUGIN DEBUG: Saving results ===")
                link_finder.save_results()
                logger.info(f"Link finder completed successfully! Found {len(link_finder.found_links)} links")
                print(f"=== PLUGIN DEBUG: Found {len(link_finder.found_links)} links ===")
                
            except ImportError as e:
                logger.error(f"Failed to import finder module: {e}")
                print(f"=== PLUGIN DEBUG: IMPORT ERROR: {e} ===")
                logger.error(f"Current working directory: {os.getcwd()}")
                logger.error(f"Files in link-finder directory: {os.listdir(link_finder_dir) if os.path.exists(link_finder_dir) else 'Directory not found'}")
            except Exception as e:
                logger.error(f"Error during finder execution: {e}")
                print(f"=== PLUGIN DEBUG: EXECUTION ERROR: {e} ===")
                logger.exception("Full exception traceback:")
                
            finally:
                # Clean up: remove from path if we added it
                if path_added and link_finder_dir in sys.path:
                    sys.path.remove(link_finder_dir)
                    logger.info("Removed link finder directory from sys.path")
                if vendor_path_added and vendor_dir in sys.path:
                    sys.path.remove(vendor_dir)
                    logger.info("Removed vendor directory from sys.path")
                
                # Restore original working directory
                os.chdir(original_cwd)
                logger.info(f"Restored working directory to: {original_cwd}")
                print("=== PLUGIN DEBUG: Cleaned up paths and directory ===")
                
        except Exception as e:
            # If link finder fails, log the error but don't break the plugin
            logger.error(f"Link finder failed to refresh data: {e}")
            print(f"=== PLUGIN DEBUG: OUTER ERROR: {e} ===")
            logger.exception("Full exception traceback:")
            # Continue with existing JSON file

    def build_tree_from_json(self):
        """Build tree structure from JSON data with nested categories."""
        if "categories" not in self.geo_links:
            return

        def build_node(parent_item, data, level=0):
            """Recursively build tree nodes from nested dict structure."""
            if isinstance(data, dict):
                for key, value in data.items():
                    if key == "links":

                        for link_data in value:
                            self.add_service_item(parent_item, link_data)
                    else:

                        category_item = QtWidgets.QTreeWidgetItem(parent_item)
                        category_item.setText(0, key)
                        category_item.setFlags(
                            category_item.flags()
                            | Qt.ItemIsUserCheckable
                            | Qt.ItemIsTristate
                        )
                        category_item.setCheckState(0, Qt.Unchecked)
                        category_item.setExpanded(False)

                        category_item.setData(0, Qt.UserRole + 2, "category")

                        build_node(category_item, value, level + 1)

        categories_data = self.geo_links["categories"]
        build_node(self.layers_tree, categories_data, 0)

    def add_service_item(self, parent_item, link_data):
        """Add a service item (leaf node with WMS/WFS link) to the tree."""
        service_name = link_data.get("link_text", "Unknown Service")
        service_type = link_data.get("service_type", "Unknown")
        url = link_data.get("url", "")

        display_text = service_name

        service_item = QtWidgets.QTreeWidgetItem(parent_item)
        service_item.setText(0, display_text)
        service_item.setFlags(
            service_item.flags() | Qt.ItemIsUserCheckable | Qt.ItemIsTristate
        )
        service_item.setCheckState(0, Qt.Unchecked)

        service_item.setData(
            0,
            Qt.UserRole,
            {
                "url": url,
                "service_type": service_type,
                "link_text": service_name,
                "is_loaded": False,
            },
        )

        service_item.setData(0, Qt.UserRole + 2, "service")

    def on_item_expanded(self, item):
        """Load layers when a service item is expanded for the first time."""
        item_type = item.data(0, Qt.UserRole + 2)

        if item_type == "service":
            service_data = item.data(0, Qt.UserRole)
            if service_data and not service_data.get("is_loaded", False):
                capabilities_url = service_data.get("url", "")
                if capabilities_url:
                    self.load_layers_for_service(item, service_data)

    def load_all_sources(self):
        """Load layers from all WMS/WFS sources recursively."""
        self.status_label.setText("Loading all sources...")
        QtWidgets.QApplication.setOverrideCursor(Qt.WaitCursor)

        total_loaded = 0
        errors = []

        try:

            def load_recursive(parent_item):
                nonlocal total_loaded, errors
                for i in range(
                    parent_item.childCount()
                    if hasattr(parent_item, "childCount")
                    else self.layers_tree.topLevelItemCount()
                ):
                    if hasattr(parent_item, "child"):
                        item = parent_item.child(i)
                    else:
                        item = self.layers_tree.topLevelItem(i)

                    item_type = item.data(0, Qt.UserRole + 2)

                    if item_type == "service":

                        service_data = item.data(0, Qt.UserRole)
                        if service_data and not service_data.get("is_loaded", False):
                            try:
                                count = self.load_layers_for_service(item, service_data)
                                total_loaded += count

                            except Exception as e:
                                errors.append("{}: {}".format(item.text(0), str(e)))
                    elif item_type == "category":

                        load_recursive(item)

            load_recursive(self.layers_tree)

            if errors:
                self.status_label.setText(
                    "Loaded {} layers with some errors. See console for details.".format(
                        total_loaded
                    )
                )
                for error in errors:
                    print("Error loading source:", error)
            else:
                self.status_label.setText(
                    "Successfully loaded {} layers from all sources. Check layers to import.".format(
                        total_loaded
                    )
                )

        finally:
            QtWidgets.QApplication.restoreOverrideCursor()

    def load_layers_for_service(self, service_item, service_data):
        """Load layers for a specific service item (WMS/WFS)."""
        capabilities_url = service_data.get("url", "")
        service_type = service_data.get("service_type", "WMS")
        service_name = service_item.text(0)

        logger.info(f"Loading layers for service: {service_name} ({service_type})")
        logger.debug(f"Capabilities URL: {capabilities_url}")

        try:

            if service_type == "WFS":
                logger.debug("Fetching WFS layers")
                layers = self.fetch_wfs_layers_from_capabilities(capabilities_url)
            else:
                logger.debug("Fetching WMS layers")
                layers = self.fetch_layers_from_capabilities(capabilities_url)

            if not layers:
                logger.warning(f"No layers found for service: {service_name}")

                placeholder = QtWidgets.QTreeWidgetItem(service_item)
                placeholder.setText(0, "(No layers available)")
                placeholder.setDisabled(True)
                service_data["is_loaded"] = True
                service_item.setData(0, Qt.UserRole, service_data)
                return 0

            logger.info(f"Found {len(layers)} layers for service: {service_name}")

            capabilities_url = service_data.get("url", "")
            stable_service_url = self._service_url_from_capabilities(capabilities_url)

            for name, title, srs_list, getmap_url in layers:
                display_text = "{}".format(title if title else name)

                logger.debug(
                    f"Adding layer item: {display_text} (name: {name}, getmap_url: {getmap_url}, stable_service_url: {stable_service_url})"
                )

                layer_item = QtWidgets.QTreeWidgetItem(service_item)
                layer_item.setText(0, display_text)
                layer_item.setFlags(layer_item.flags() | Qt.ItemIsUserCheckable)
                layer_item.setCheckState(0, Qt.Unchecked)

                layer_item.setData(
                    0,
                    Qt.UserRole,
                    {
                        "name": name,
                        "title": title,
                        "srs": srs_list,
                        "url": getmap_url,
                        "service_url": stable_service_url,
                        "service_type": service_type,
                    },
                )

                layer_item.setData(0, Qt.UserRole + 2, "layer")

            service_data["is_loaded"] = True
            service_item.setData(0, Qt.UserRole, service_data)
            return len(layers)

        except Exception as e:
            error_msg = f"Error loading layers for service '{service_name}': {str(e)}"
            logger.error(error_msg)
            logger.exception("Full exception details:")

            error_item = QtWidgets.QTreeWidgetItem(service_item)
            error_item.setText(0, "(Error loading: {})".format(str(e)))
            error_item.setDisabled(True)
            service_data["is_loaded"] = True
            service_item.setData(0, Qt.UserRole, service_data)
            raise

    def fetch_layers_from_capabilities(self, capabilities_url):
        """Fetch WMS capabilities and extract layer information."""
        logger.info(f"Fetching WMS capabilities from: {capabilities_url}")

        import xml.etree.ElementTree as ET
        from qgis.PyQt.QtNetwork import QNetworkAccessManager, QNetworkRequest
        from qgis.PyQt.QtCore import QEventLoop, QUrl

        manager = QNetworkAccessManager()
        request = QNetworkRequest()
        request.setUrl(QUrl(capabilities_url))
        loop = QEventLoop()

        reply = manager.get(request)
        reply.finished.connect(loop.quit)
        loop.exec_()

        if reply.error():
            error_msg = f"Network error fetching capabilities: {reply.errorString()}"
            logger.error(error_msg)
            raise RuntimeError(error_msg)

        data = bytes(reply.readAll())
        logger.debug(f"Received {len(data)} bytes of capabilities data")

        try:
            root = ET.fromstring(data)
            logger.debug("Successfully parsed capabilities XML")
        except ET.ParseError as e:
            error_msg = f"Failed to parse capabilities XML: {e}"
            logger.error(error_msg)
            logger.debug(f"Raw data (first 1000 chars): {data[:1000]}")
            raise RuntimeError(error_msg)

        def find_text(elem, tag):
            t = elem.find(tag)
            return t.text if t is not None else None

        base_url = None
        capability = root.find("Capability")
        logger.debug(f"Capability element found: {capability is not None}")

        if capability is not None:
            request_elem = capability.find("Request")
            logger.debug(f"Request element found: {request_elem is not None}")

            if request_elem is not None:
                getmap = request_elem.find("GetMap")
                logger.debug(f"GetMap element found: {getmap is not None}")

                if getmap is not None:
                    dcptype = getmap.find("DCPType")
                    if dcptype is not None:
                        http = dcptype.find("HTTP")
                        if http is not None:
                            get = http.find("Get")
                            if get is not None:
                                online_resource = get.find("OnlineResource")
                                if online_resource is not None:
                                    base_url = online_resource.get(
                                        "{http://www.w3.org/1999/xlink}href"
                                    )
                                    if not base_url:
                                        base_url = online_resource.get("href")
                                    logger.info(
                                        f"Extracted GetMap URL from capabilities: {base_url}"
                                    )

        if not base_url:
            from urllib.parse import urlsplit, urlunsplit

            parts = urlsplit(capabilities_url)
            base_url = urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))
            logger.warning(
                f"GetMap URL not found in capabilities, using fallback: {base_url}"
            )

        base_url = base_url.rstrip("&")
        logger.info(f"Final base URL for WMS requests: {base_url}")

        def walk_layer(layer_elem, collected):
            name = find_text(layer_elem, "Name")
            title = find_text(layer_elem, "Title") or name

            srs_list = []
            for srs_elem in layer_elem.findall("SRS"):
                if srs_elem.text:
                    srs_list.append(srs_elem.text)
            for crs_elem in layer_elem.findall("CRS"):
                if crs_elem.text:
                    srs_list.append(crs_elem.text)

            child_layers = layer_elem.findall("Layer")
            has_children = len(child_layers) > 0

            if name and not has_children:
                logger.debug(
                    f"Found layer: name='{name}', title='{title}', srs={srs_list}"
                )
                collected.append((name, title, srs_list, base_url))
            elif name:
                logger.debug(
                    f"Skipping container layer: name='{name}', children={len(child_layers)}"
                )

            for child in child_layers:
                walk_layer(child, collected)

        layers = []
        capability = root.find("Capability")
        if capability is None:
            capability = root
            logger.debug(
                "Using root element as capability (no Capability element found)"
            )

        logger.debug("Starting layer extraction from capabilities")
        for layer_elem in capability.findall("Layer"):
            walk_layer(layer_elem, layers)

        logger.info(f"Extracted {len(layers)} layers from capabilities")
        return layers

    def _service_url_from_capabilities(self, capabilities_url: str) -> str:
        """Return a stable Mapbender service URL for QGIS to start from (not the proxy)."""
        from urllib.parse import urlsplit, urlunsplit, parse_qs

        parts = urlsplit(capabilities_url)
        q = parse_qs(parts.query)
        layer_id = q.get("layer_id", [""])[0]
        base = urlunsplit(
            (parts.scheme, parts.netloc, "/mapbender/php/wms.php", "", "")
        )

        if layer_id:
            return f"{base}?layer_id={layer_id}&withChilds=1&SERVICE=WMS&VERSION=1.1.1"
        return f"{base}?withChilds=1&SERVICE=WMS&VERSION=1.1.1"

    def fetch_wfs_layers_from_capabilities(self, capabilities_url):
        """Fetch WFS capabilities and extract feature type information."""
        import xml.etree.ElementTree as ET
        from qgis.PyQt.QtNetwork import QNetworkAccessManager, QNetworkRequest
        from qgis.PyQt.QtCore import QEventLoop, QUrl

        manager = QNetworkAccessManager()
        request = QNetworkRequest()
        request.setUrl(QUrl(capabilities_url))
        loop = QEventLoop()

        reply = manager.get(request)
        reply.finished.connect(loop.quit)
        loop.exec_()

        if reply.error():
            raise RuntimeError("Network error: {}".format(reply.errorString()))

        data = bytes(reply.readAll())

        root = ET.fromstring(data)

        namespaces = {
            "wfs": "http://www.opengis.net/wfs/2.0",
            "wfs11": "http://www.opengis.net/wfs",
            "ows": "http://www.opengis.net/ows/1.1",
        }

        feature_type_list = root.find("wfs:FeatureTypeList", namespaces)
        if feature_type_list is None:
            feature_type_list = root.find("wfs11:FeatureTypeList", namespaces)
        if feature_type_list is None:
            feature_type_list = root.find("FeatureTypeList")

        if feature_type_list is None:
            return []

        layers = []

        from urllib.parse import urlsplit, urlunsplit, parse_qs, urlencode

        parts = urlsplit(capabilities_url)

        query_params = parse_qs(parts.query)
        essential_params = {}
        if "FEATURETYPE_ID" in query_params:
            essential_params["FEATURETYPE_ID"] = query_params["FEATURETYPE_ID"][0]

        new_query = urlencode(essential_params) if essential_params else ""

        base_url = urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))
        if new_query:
            base_url = base_url + "?" + new_query

        feature_types = feature_type_list.findall("wfs:FeatureType", namespaces)
        if not feature_types:
            feature_types = feature_type_list.findall("wfs11:FeatureType", namespaces)
        if not feature_types:
            feature_types = feature_type_list.findall("FeatureType")

        for ft in feature_types:

            name_elem = ft.find("wfs:Name", namespaces)
            if name_elem is None:
                name_elem = ft.find("wfs11:Name", namespaces)
            if name_elem is None:
                name_elem = ft.find("Name")

            name = name_elem.text if name_elem is not None else None

            title_elem = ft.find("wfs:Title", namespaces)
            if title_elem is None:
                title_elem = ft.find("wfs11:Title", namespaces)
            if title_elem is None:
                title_elem = ft.find("Title")

            title = title_elem.text if title_elem is not None else name

            srs_list = []

            default_crs = ft.find("wfs:DefaultCRS", namespaces)
            if default_crs is not None and default_crs.text:

                crs_text = default_crs.text
                if "EPSG" in crs_text:

                    if "::" in crs_text:
                        epsg_code = crs_text.split("::")[-1]
                        srs_list.append("EPSG:{}".format(epsg_code))
                    else:
                        srs_list.append(crs_text)

            other_crs_list = ft.findall("wfs:OtherCRS", namespaces)
            for other_crs in other_crs_list:
                if other_crs.text and "EPSG" in other_crs.text:
                    if "::" in other_crs.text:
                        epsg_code = other_crs.text.split("::")[-1]
                        srs_list.append("EPSG:{}".format(epsg_code))
                    else:
                        srs_list.append(other_crs.text)

            if not srs_list:
                srs_elem = ft.find("wfs11:SRS", namespaces)
                if srs_elem is None:
                    srs_elem = ft.find("SRS")
                if srs_elem is not None and srs_elem.text:
                    srs_list.append(srs_elem.text)

            if not srs_list:
                srs_list = ["EPSG:25832", "EPSG:3857"]

            if name:
                layers.append((name, title, srs_list, base_url))

        return layers

    def reset_selection(self):
        """Reset all selections in the tree widget by unchecking all items."""

        def uncheck_all(item):
            """Recursively uncheck all items."""

            item.setCheckState(0, Qt.Unchecked)

            for i in range(item.childCount()):
                uncheck_all(item.child(i))

        for i in range(self.layers_tree.topLevelItemCount()):
            uncheck_all(self.layers_tree.topLevelItem(i))

    def get_selected_layers(self):
        """Return list of checked layer data from tree recursively."""
        selected = []

        def collect_checked(item):
            """Recursively collect checked layer items."""
            item_type = item.data(0, Qt.UserRole + 2)

            if item_type == "layer" and item.checkState(0) == Qt.Checked:
                layer_data = item.data(0, Qt.UserRole)
                if layer_data and isinstance(layer_data, dict):
                    selected.append(layer_data)

            for i in range(item.childCount()):
                collect_checked(item.child(i))

        for i in range(self.layers_tree.topLevelItemCount()):
            collect_checked(self.layers_tree.topLevelItem(i))

        return selected
